version: '3'

services:
  db:
    container_name: caller_squid_db
    image: postgres:14
    environment:
      #      POSTGRES_DB: squid
      #      POSTGRES_PASSWORD: squid
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - '${DB_PORT}:5432'
      # command: ["postgres", "-c", "log_statement=all"]
    #    volumes:
    #      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env
