manifestVersion: subsquid.io/v0.1
name: caller-squid-moonbeam
version: 2
description: |-
  Caller squid for Moonbeam
build:

deploy:
  addons:
    postgres:
  processor:
    env:
      CHAIN:
        moonbeam
    cmd: [ "node", "lib/processor" ]
  api:
    cmd: [ "npx", "squid-graphql-server", "--dumb-cache", "in-memory", "--dumb-cache-ttl", "1000", "--dumb-cache-size", "100", "--dumb-cache-max-age", "1000" ]

scale:
  addons:
     postgres:
         storage: 100G
         profile: large